name: Publish artifacts

on:
  push:
    tags: 
      - '*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm install
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-docker-hub:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker build and push
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker build --file Dockerfile --tag kyso/kyso:${{github.ref_name}} --build-arg PACKAGE_VERSION=${{github.ref_name}} .
        docker build --file Dockerfile --tag kyso/kyso:latest --build-arg PACKAGE_VERSION=${{github.ref_name}} .
        docker push kyso/kyso:${{github.ref_name}}    
        docker push kyso/kyso:latest    